version: '3'

services:
  frontend:
    # build: frontend
    image: ghcr.io/dliebg/schwering_app/frontend:main
    container_name: schwering_app_frontend
    restart: unless-stopped
    ports:
      - 80:80
    networks:
      macvlan:
        ipv4_address: 10.16.1.1
      default:

  backend:
    # build: backend
    image: ghcr.io/dliebg/schwering_app/backend:main
    container_name: schwering_app_backend
    restart: unless-stopped
    env_file: .env

networks:
  macvlan:
    driver: macvlan
    driver_opts:
      parent: eth0
    ipam:
      config:
        - subnet: 10.16.0.0/16
